branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "alpha"
    prerelease: "alpha"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION"
  - - "@semantic-release/changelog"
    - changelogTitle: |-
        # Change Log

        All notable changes to this project will be documented in this file and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
        See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - README.md
        - docs/*
      message: "chore(release): v${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/gitlab"


verifyConditions:
  - "@semantic-release/git"
  - "@semantic-release/gitlab"

analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
      - type: "no-release"
        release: false
      - type: "chore"
        release: false
      - type: "revert"
        release: false
      - type: "fix"
        release: "patch"
      - type: "hotfix"
        release: "patch"
      - type: "perf"
        release: "patch"
      - type: "test"
        release: "patch"
      - type: "docs"
        release: "patch"
      - type: "style"
        release: "patch"
      - type: "refactor"
        release: "patch"
      - type: "patch"
        release: "patch"
      - type: "feat"
        release: "minor"
      - type: "minor"
        release: "minor"
      - type: "BREAKING CHANGE"
        release: "major"
      - type: "major"
        release: "major"

generateNotes:
  - path: "@semantic-release/release-notes-generator"
    writerOpts:
      groupBy: "type"
      commitGroupsSort:
        - "feat"
        - "perf"
        - "fix"
      commitsSort: "header"
    types:
      - type: "major"
      - section: "Features"
      - type: "BREAKING CHANGE"
      - section: "Breaking Changes"
      - type: "minor"
      - section: "Features"
      - type: "feat"
      - section: "Features"
      - type: "patch"
      - section: "Bug Fixes"
      - type: "hotfix"
      - section: "Bug Fixes"
      - type: "fix"
      - section: "Bug Fixes"
      - type: "revert"
      - section: "Revert"
      - type: "no-release"
      - hidden: true
      - type: "chore"
      - hidden: true
      - type: "perf"
      - hidden: true
      - type: "test"
      - hidden: true
      - type: "docs"
      - hidden: true
      - type: "style"
      - hidden: true
      - type: "refactor"
      - hidden: true
    presetConfig: true
